export const commonStyles = {
  container: {
    flex: 1,
    alignItems: "center",
  },
  containerInput: {
    alignItems: "center",
    justifyContent: "center",
    width: "90%",
    margin: 5,
  },
  button: {
    alignItems: "center",
    justifyContent: "center",
  },
  button33: {
    alignItems: "center",
    justifyContent: "center",
    width: "33%",
    padding: 4,
    margin: 3,
    marginTop: 5,
    marginBottom: 1,
  },
  button50: {
    alignItems: "center",
    justifyContent: "center",
    width: "50%",
    padding: 4,
    margin: 3,
    marginTop: 5,
    marginBottom: 1,
  },
  button100: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    padding: 4,
    margin: 3,
    marginTop: 5,
    marginBottom: 1,
  },
  buttonText: {
    fontWeight: "400",
    fontSize: 20,
    padding: 10,
    color: "yellow",
  },
  title: {
    fontWeight: "bold",
    fontSize: 30,
    padding: 20,
    textAlign: "center",
  },
  text: {
    fontSize: 16,
  },
  content: {
    fontWeight: "400",
    fontSize: 24,
  },
  backgroundGradient: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 400,
  },
  switchText: {
    fontWeight: "400",
    fontSize: 20,
    marginTop: 20,
  },
  inputView: {
    width: "100%",
    marginBottom: 20,
    borderRadius: 0,
    alignItems: "center",
  },
  textInput: {
    width: "100%",
    fontSize: 20,
    textAlign: "center",
    height: 30,
    backgroundColor: "transparent",
  },
  errorText: {
    fontSize: 15,
    color: "red",
    marginTop: 20,
  },
  header: {
    height: 100,
    shadowOpacity: 0.2,
    shadowRadius: 5,
    shadowColor: "black",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
  },
  boldText: {
    fontWeight: "bold",
    fontSize: 18,
  },
  logo: {
    width: 120,
    height: 120,
    borderBottomRightRadius: 40,
    borderTopLeftRadius: 40,
  },
  logo100: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
};
